#!/usr/bin/env perl
# Inspired by @trisweb's code on this wiki page:
# http://github.com/holman/spark/wiki/Wicked-Cool-Usage 

use strict;
use warnings;

use Getopt::Long::Descriptive;
use DateTime;

my ($option, $usage) = describe_options(
    'usage: git spark %o [AUTHOR]',
    ['hours|o=i'      => 'commits from the last x hours'],
    ['days|d=i'       => 'commits from the last x days'],
    ['weeks|w=i'      => 'commits from the last x weeks'],
    ['months|m=i'     => 'commits from the last x months'],
    ['years|y=i'      => 'commits from the last x years'],
    ['max|m=i'        => 'max value.  used to scale graph. defaults to 50'],
    ['help|h'         => 'show this message'],
);

my $author = $ARGV[0] || $ENV{USER};
my $max    = $option->{max} || 50;

print($usage), exit 0 if $option->{help};
print($usage), exit 0 
    if (!$option->{hours}  && 
        !$option->{days}   && 
        !$option->{weeks}  && 
        !$option->{months} && 
        !$option->{years});

foreach my $key (qw/hours days weeks months years/) {
    spark($option->{$key}, $key, $author, $max ) if $option->{$key};
}

sub spark {
    my ($value, $units, $author, $max) = @_;
    my $data = countCommits(@_);
    print "Commits by $author over the last $value $units\n";
    print "$data\n";
    print `spark $data 100`;
}

sub countCommits {
    my ($value, $units, $author, $max) = @_;

    my @commits;
    foreach my $i (0..$value) {
        my $cmd = "git log " .
                  "--author=${author} " .
                  "--before='${i} ${units}' " . 
                  "--after='" . ($i + 1) . " ${units}' " .
                  "--format=oneline | wc -l";
        my $count = `$cmd`;
        chomp($count);
        push @commits, $count;
    }

    return join(" ", $max, reverse @commits);
}

