=pod

=encoding utf-8

=head1 NAME

App::Git::Spark - Review the latest changes to a git repository

=head1 SYNOPSIS

  git spark

=head2 DESCRIPTION

TODO

=head1 AUTHOR

Eric Johnson <cpan at iijo dot nospamthanks dot org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2013 by Eric Johnson.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

